"""add_server_defaults

Revision ID: 38e1e5378999
Revises: 67e8fe0f6728
Create Date: 2026-03-30 06:05:24.031114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e1e5378999'
down_revision: Union[str, Sequence[str], None] = '67e8fe0f6728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # UUID server defaults
    for table in [
        "job_roles", "job_descriptions", "job_scoring_config",
        "resume_uploads", "candidates", "candidate_skills",
        "candidate_experience", "job_matches",
    ]:
        op.alter_column(table, "id", server_default=sa.text("uuid_generate_v4()"))

    # job_roles
    op.alter_column("job_roles", "is_active", server_default=sa.true())

    # job_descriptions
    op.alter_column("job_descriptions", "is_active", server_default=sa.true())

    # job_scoring_config
    op.alter_column("job_scoring_config", "preset_name",    server_default="Default")
    op.alter_column("job_scoring_config", "skill_match_weight", server_default=sa.text("40"))
    op.alter_column("job_scoring_config", "exp_years_weight",   server_default=sa.text("20"))
    op.alter_column("job_scoring_config", "projects_weight",    server_default=sa.text("20"))
    op.alter_column("job_scoring_config", "prof_exp_weight",    server_default=sa.text("15"))
    op.alter_column("job_scoring_config", "certs_weight",       server_default=sa.text("5"))
    op.alter_column("job_scoring_config", "is_customised",  server_default=sa.false())

    # resume_uploads
    op.alter_column("resume_uploads", "status",     server_default="uploaded")
    op.alter_column("resume_uploads", "batch_date", server_default=sa.text("CURRENT_DATE"))

    # candidates
    op.alter_column("candidates", "total_exp_years",    server_default=sa.text("0"))
    op.alter_column("candidates", "is_low_confidence",  server_default=sa.false())

    # candidate_skills — proficiency is nullable, nothing needed
    # candidate_experience
    op.alter_column("candidate_experience", "is_current", server_default=sa.false())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tables = [
        "job_roles",
        "job_descriptions",
        "job_scoring_config",
        "resume_uploads",
        "candidates",
        "candidate_skills",
        "candidate_experience",
        "job_matches",
    ]
    for table in tables:
        op.alter_column(table, "id", server_default=None)
    # ### end Alembic commands ###
