"""initial_schema

Revision ID: 67e8fe0f6728
Revises: 
Create Date: 2026-03-30 05:50:46.191532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '67e8fe0f6728'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('job_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('requirements_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jd_embedding', 'job_descriptions', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_jd_job_role', 'job_descriptions', ['job_role_id'], unique=False)
    op.create_table('job_scoring_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('preset_name', sa.String(length=100), nullable=False),
    sa.Column('skill_match_weight', sa.SmallInteger(), nullable=False),
    sa.Column('exp_years_weight', sa.SmallInteger(), nullable=False),
    sa.Column('projects_weight', sa.SmallInteger(), nullable=False),
    sa.Column('prof_exp_weight', sa.SmallInteger(), nullable=False),
    sa.Column('certs_weight', sa.SmallInteger(), nullable=False),
    sa.Column('is_customised', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.CheckConstraint('certs_weight BETWEEN 0 AND 100', name='certs_range'),
    sa.CheckConstraint('exp_years_weight BETWEEN 0 AND 100', name='exp_years_range'),
    sa.CheckConstraint('prof_exp_weight BETWEEN 0 AND 100', name='prof_exp_range'),
    sa.CheckConstraint('projects_weight BETWEEN 0 AND 100', name='projects_range'),
    sa.CheckConstraint('skill_match_weight + exp_years_weight + projects_weight + prof_exp_weight + certs_weight = 100', name='weights_sum_100'),
    sa.CheckConstraint('skill_match_weight BETWEEN 0 AND 100', name='skill_match_range'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_role_id')
    )
    op.create_table('resume_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'queued', 'parsing', 'parsed', 'failed', name='upload_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('batch_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resume_uploads_batch', 'resume_uploads', ['batch_date'], unique=False)
    op.create_index('idx_resume_uploads_job_role', 'resume_uploads', ['job_role_id'], unique=False)
    op.create_index('idx_resume_uploads_status', 'resume_uploads', ['status'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_upload_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('total_exp_years', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('is_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_upload_id'], ['resume_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_upload_id')
    )
    op.create_index('idx_candidates_embedding', 'candidates', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_candidates_exp_years', 'candidates', ['total_exp_years'], unique=False)
    op.create_table('candidate_experience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('exp_type', sa.Enum('professional', 'internship', 'project', 'freelance', 'volunteer', name='experience_type'), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_exp_candidate', 'candidate_experience', ['candidate_id'], unique=False)
    op.create_index('idx_candidate_exp_type', 'candidate_experience', ['exp_type'], unique=False)
    op.create_table('candidate_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('skill_category', sa.String(length=50), nullable=True),
    sa.Column('source', sa.Enum('professional', 'project', 'internship', 'certification', 'education', name='skill_source'), nullable=False),
    sa.Column('proficiency', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('proficiency BETWEEN 1 AND 5', name='candidate_skills_proficiency_check'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_skills_candidate', 'candidate_skills', ['candidate_id'], unique=False)
    op.create_index('idx_candidate_skills_category', 'candidate_skills', ['skill_category'], unique=False)
    op.create_index('idx_candidate_skills_name', 'candidate_skills', ['skill_name'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jd_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('semantic_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rule_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('score_breakdown_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('justification_text', sa.Text(), nullable=True),
    sa.Column('justification_model', sa.String(length=100), nullable=True),
    sa.Column('ranked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jd_id', 'candidate_id', name='uq_job_matches_jd_candidate')
    )
    op.create_index('idx_job_matches_final_score', 'job_matches', ['jd_id', 'final_score'], unique=False)
    op.create_index('idx_job_matches_jd', 'job_matches', ['jd_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_matches_jd', table_name='job_matches')
    op.drop_index('idx_job_matches_final_score', table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index('idx_candidate_skills_name', table_name='candidate_skills')
    op.drop_index('idx_candidate_skills_category', table_name='candidate_skills')
    op.drop_index('idx_candidate_skills_candidate', table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_index('idx_candidate_exp_type', table_name='candidate_experience')
    op.drop_index('idx_candidate_exp_candidate', table_name='candidate_experience')
    op.drop_table('candidate_experience')
    op.drop_index('idx_candidates_exp_years', table_name='candidates')
    op.drop_index('idx_candidates_embedding', table_name='candidates', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('candidates')
    op.drop_index('idx_resume_uploads_status', table_name='resume_uploads')
    op.drop_index('idx_resume_uploads_job_role', table_name='resume_uploads')
    op.drop_index('idx_resume_uploads_batch', table_name='resume_uploads')
    op.drop_table('resume_uploads')
    op.drop_table('job_scoring_config')
    op.drop_index('idx_jd_job_role', table_name='job_descriptions')
    op.drop_index('idx_jd_embedding', table_name='job_descriptions', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('job_descriptions')
    op.drop_table('job_roles')
    # ### end Alembic commands ###
